habit_gallery/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from habit_gallery.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('habits.urls'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

habits/urls.py
from django.urls import path
from django.views.generic import RedirectView

from habits.views import (
    add_habit_view, habit_list_view, habit_detail_view,
    habit_current_list_view, habit_new_painting_view, habit_painting_detail_view, edit_habit_view,
    delete_habit_view,
)

urlpatterns = [
    path('', RedirectView.as_view(url='current/', permanent=False), name='main'),
    path('current/', habit_current_list_view, name='habit-current-list'),
    path('habits/', habit_list_view, name='habit-list'),
    path('habits/add/', add_habit_view, name='add-habit'),
    path('habits/<int:pk>/', habit_detail_view, name='habit-detail'),
    path('habits/<int:pk>/edit/', edit_habit_view, name='edit-habit'),
    path('habits/<int:pk>/delete/', delete_habit_view, name='delete-habit'),
    path('habits/<int:pk>/new_painting/', habit_new_painting_view, name='habit-new-painting'),
    path('painting/<int:pk>/', habit_painting_detail_view, name='habit-painting-detail')
]

habits/models.py
from django.db import models

from accounts.models import User
from habits.choices import HabitTypes, HabitPaintingTypes, HabitDeadlineCheckStatus

NULLABLE = {'blank': True, 'null': True}


class Habit(models.Model):
    type = models.CharField(
        verbose_name='Тип',
        max_length=15,
        choices=HabitTypes.choices,
        default=HabitTypes.DAILY
    )
    name = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    start_date = models.DateField(
        verbose_name='Дата начала'
    )
    frequency = models.PositiveIntegerField(
        verbose_name='Частота',
        help_text='Каждые n дней/недель/месяцев',
        default=1
    )
    required_amount = models.PositiveIntegerField(
        verbose_name='Нужное количество',
        help_text='За 1 день/неделю/месяц',
        default=1
    )

    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE
    )
    completed_amount = models.PositiveIntegerField(
        verbose_name='Выполненное количество',
        default=0
    )
    current_streak = models.PositiveIntegerField(
        verbose_name='Текущее значение стрика',
        default=0
    )

    # If type is either 'weekly' or 'monthly'
    selected_days = models.JSONField(
        verbose_name='Выбранные дни',
        help_text='Дни недели / Числа месяца',
        default=list
    )
    required_amount_per_day = models.PositiveIntegerField(
        verbose_name='Нужное количество в день',
        default=1
    )

    @property
    def current_required_amount(self):
        if self.type == 'daily' or not self.selected_days:
            return self.required_amount
        else:
            return self.required_amount_per_day

    @property
    def complete_percentage(self):
        return min(round(self.completed_amount / self.current_required_amount * 100), 100)

    @property
    def painting_cnt(self):
        return (
            self.habitpainting_set
            .filter(type__in=[
                HabitPaintingTypes.PARTIALLY_COMPLETED,
                HabitPaintingTypes.COMPLETED
            ])
            .count()
        )

    class Meta:
        verbose_name = 'Привычка'
        verbose_name_plural = 'Привычки'


class HabitPainting(models.Model):
    habit = models.ForeignKey(
        Habit,
        verbose_name='Привычка',
        on_delete=models.CASCADE
    )
    type = models.CharField(
        verbose_name='Тип',
        max_length=31,
        choices=HabitPaintingTypes.choices
    )

    # If type is not 'pre_generated'
    date = models.DateField(
        verbose_name='Дата получения',
        **NULLABLE
    )

    # If type is 'completed'
    painting = models.ImageField(
        verbose_name='Картина',
        upload_to='paintings',
        **NULLABLE
    )

    # If type is 'completed' or 'pre_generated'
    painting_name = models.CharField(
        verbose_name='Название картины',
        max_length=255,
        **NULLABLE
    )


class HabitDeadlineCheck(models.Model):
    date = models.DateField(
        verbose_name='Дата проведения'
    )
    status = models.CharField(
        verbose_name='Статус',
        max_length=31,
        choices=HabitDeadlineCheckStatus.choices
    )

habits/forms/edit_habit.py
from django import forms

from habits.models import Habit


class EditHabitForm(forms.ModelForm):
    name = forms.CharField(
        label='Новое название',
        widget=forms.TextInput(attrs={'placeholder': 'Введите новое название'})
    )

    class Meta:
        model = Habit
        fields = ('name',)

habits/forms/fields.py
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class DateField(forms.DateField):
    widget = DateInput

habits/forms/habit_current_list.py
from django import forms


class OrderHabitForm(forms.Form):
    order = forms.ChoiceField(
        label='Сортировка',
        choices=(('deadline', 'Deadline asc'), ('-deadline', 'Deadline desc'))
    )

habits/forms/habit_detail.py
from django import forms


class CalendarHabitForm(forms.Form):
    calendar_date = forms.DateField()

habits/views/add_habit.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone

from habits.choices import HabitTypes
from habits.forms import AddDailyHabitForm
from habits.forms.add_habit import (
    AddFlexibleWeeklyHabitForm, AddFixedWeeklyHabitForm,
    AddFlexibleMonthlyHabitForm, AddFixedMonthlyHabitForm,
)
from habits.models import Habit
from habits.tasks import pre_generate_painting
from habits.utils import bool_str_to_bool


@login_required(redirect_field_name='', login_url='/login/')
def add_habit_view(request):
    habit_type = request.GET.get('type', HabitTypes.DAILY)
    is_flexible = bool_str_to_bool(request.GET.get('flexible', 'true'))

    form_class = AddDailyHabitForm
    if habit_type == HabitTypes.WEEKLY:
        form_class = AddFlexibleWeeklyHabitForm if is_flexible else AddFixedWeeklyHabitForm
    elif habit_type == HabitTypes.MONTHLY:
        form_class = AddFlexibleMonthlyHabitForm if is_flexible else AddFixedMonthlyHabitForm

    form = form_class(initial={'type': habit_type})

    if request.method == 'POST':
        is_flexible = 'selected_days' not in request.POST
        form = form_class(request.POST, request=request)
        if form.is_valid():
            habit = Habit.objects.create(**form.cleaned_data)
            pre_generate_painting.delay(habit.pk)
            return redirect('habit-list')

    header_left_btn_url = reverse('habit-list')
    return render(request, 'habits/add_habit.html', locals())

habits/views/delete_habit.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from habits.models import Habit


@login_required(redirect_field_name='', login_url='/login/')
def delete_habit_view(request, pk=None):
    habit = get_object_or_404(Habit, pk=pk, author=request.user)
    habit.delete()
    return redirect('habit-list')

habits/views/edit_habit.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from habits.forms.edit_habit import EditHabitForm
from habits.models import Habit


@login_required(redirect_field_name='', login_url='/login/')
def edit_habit_view(request, pk=None):
    habit = get_object_or_404(Habit, pk=pk, author=request.user)
    form = EditHabitForm(initial={'name': habit.name})
    if request.method == 'POST':
        form = EditHabitForm(request.POST)
        if form.is_valid():
            habit.name = form.cleaned_data.get('name')
            habit.save(update_fields=['name'])
            return redirect('habit-detail', pk=pk)
    return render(request, 'habits/edit_habit.html', locals())

habits/views/habit_current_list.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from habits.forms import OrderHabitForm
from habits.models import Habit
from habits.tasks import pre_generate_painting
from habits.utils import get_deadline


@login_required(redirect_field_name='', login_url='/login/')
def habit_current_list_view(request):
    order_field = request.GET.get('order', 'deadline')
    order_form = OrderHabitForm({'order': order_field})
    if not order_form.is_valid():
        raise Http404

    if request.method == 'POST':
        h = get_object_or_404(Habit, pk=request.POST.get('habit_id'), author=request.user)
        if h.completed_amount >= h.current_required_amount:
            raise Http404
        h.completed_amount += 1
        h.save(update_fields=['completed_amount'])
        if h.completed_amount == h.current_required_amount:
            pre_generate_painting.delay(h.pk)
            h.current_streak += 1
            h.save(update_fields=['current_streak'])
            return redirect('habit-new-painting', pk=h.pk)
        return redirect(reverse('habit-current-list') + f'?order={order_field}')

    habits = []
    today = datetime.date.today()
    for habit in Habit.objects.filter(author=request.user):
        habit.deadline = get_deadline(habit, today)
        if habit.deadline:
            habits.append(habit)
    habits.sort(key=lambda x: (x.deadline, x.name), reverse=order_field[:1] == '-')

    return render(request, 'habits/habit_current_list.html', locals())

habits/views/habit_detail.py
import calendar
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from habits.choices import HabitCalendarDayTypes, HabitTypes, HabitPaintingTypes
from habits.dataclasses import HabitCalendarDay
from habits.forms import CalendarHabitForm
from habits.models import Habit, HabitPainting
from habits.utils import (
    is_day_expected, get_first_date_of_week,
    get_last_date_of_week, get_first_date_of_month, get_last_date_of_month, is_last_selected_day,
)


@login_required(redirect_field_name='', login_url='/login/')
def habit_detail_view(request, pk=None):
    today = datetime.date.today()
    calendar_date = request.GET.get('calendar_date', today.strftime('%Y-%m-%d'))
    calendar_form = CalendarHabitForm({'calendar_date': calendar_date})
    if not calendar_form.is_valid():
        raise Http404
    calendar_date = calendar_form.cleaned_data.get('calendar_date')

    habit = get_object_or_404(Habit, pk=pk, author=request.user)

    calendar_rows = []
    for days_row in calendar.monthcalendar(calendar_date.year, calendar_date.month):
        row = []
        for day in days_row:
            # If day is not in a current month
            if day == 0:
                row.append(HabitCalendarDay(type=HabitCalendarDayTypes.NONE))
                continue

            current_date = datetime.date(calendar_date.year, calendar_date.month, day)

            # If day has a painting (partially completed, completed or missed)
            if current_date <= today:
                painting = HabitPainting.objects.filter(
                    ~Q(type=HabitPaintingTypes.PRE_GENERATED),
                    habit=habit,
                    date=current_date
                ).first()
                if painting:
                    row.append(HabitCalendarDay(
                        type=painting.type,
                        num=day,
                        painting=painting
                    ))
                    continue
                elif not painting and current_date != today:
                    row.append(HabitCalendarDay(
                        type=HabitCalendarDayTypes.EMPTY,
                        num=day
                    ))
                    continue

            # If day is expected to have a painting in the future
            if current_date >= today:
                # If days of the week/month are specified
                if habit.selected_days:
                    if is_day_expected(habit, current_date):
                        # If last day of the week/month (gets completed painting)
                        if is_last_selected_day(habit, current_date)[0]:
                            row.append(HabitCalendarDay(
                                type=HabitCalendarDayTypes.EXPECTED_FULL,
                                num=day
                            ))
                            continue
                        # If not last day of the week/month (gets part of the painting)
                        else:
                            row.append(HabitCalendarDay(
                                type=HabitCalendarDayTypes.EXPECTED_PART,
                                num=day
                            ))
                            continue

                # If days of the week/month are not specified
                else:
                    date_gte, date_lte = None, None
                    if habit.type == HabitTypes.WEEKLY:
                        date_gte = get_first_date_of_week(current_date)
                        date_lte = get_last_date_of_week(current_date)
                    elif habit.type == HabitTypes.MONTHLY:
                        date_gte = get_first_date_of_month(current_date)
                        date_lte = get_last_date_of_month(current_date)
                    # If painting has been already given that week/month previously
                    if (
                        date_gte and date_lte and
                        HabitPainting.objects
                        .filter(habit=habit, date__gte=date_gte, date__lte=date_lte)
                        .exists()
                    ):
                        row.append(HabitCalendarDay(
                            type=HabitCalendarDayTypes.EMPTY,
                            num=day,
                        ))
                        continue
                    if is_day_expected(habit, current_date):
                        row.append(HabitCalendarDay(
                            type=HabitCalendarDayTypes.EXPECTED_FULL,
                            num=day,
                        ))
                        continue

            # If day is in a current month, but doesn't have any features
            row.append(HabitCalendarDay(
                type=HabitCalendarDayTypes.EMPTY,
                num=day,
            ))

        calendar_rows.append(row)

    header_left_btn_url = reverse('habit-list')
    header_right_btn_type = 'edit_habit'
    header_right_btn_url = reverse('edit-habit', args=(pk,))
    return render(request, 'habits/habit_detail.html', locals())

habits/views/habit_list.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from habits.choices import HabitTypes
from habits.forms import SearchHabitForm
from habits.models import Habit


@login_required(redirect_field_name='', login_url='/login/')
def habit_list_view(request):
    search_form = SearchHabitForm(request.GET)
    search_term = search_form.cleaned_data.get('search') if search_form.is_valid() else None

    habits_with_type = []
    for value, label in HabitTypes.choices:
        habits_with_type.append((
            label.replace('ая', 'ые'),
            Habit.objects.filter(
                author=request.user,
                type=value,
                **({'name__icontains': search_term} if search_term else {})
            ).order_by('name')
        ))

    return render(request, 'habits/habit_list.html', locals())

habits/views/habit_new_painting.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from habits.choices import HabitPaintingTypes, HabitTypes
from habits.models import HabitPainting, Habit
from habits.utils import is_last_selected_day


@login_required(redirect_field_name='', login_url='/login/')
def habit_new_painting_view(request, pk=None):
    today = datetime.date.today()
    habit = get_object_or_404(Habit, pk=pk, author=request.user)

    new_painting = (
        HabitPainting.objects
        .filter(habit=habit, type=HabitPaintingTypes.PRE_GENERATED)
        .order_by('id')
        .first()
    )

    if (
        not new_painting or
        habit.completed_amount != habit.current_required_amount or
        HabitPainting.objects.filter(habit=habit, date=today).exists()
    ):
        raise Http404

    new_painting.date = today
    new_painting.type = HabitPaintingTypes.COMPLETED
    is_last_part, current_part_index = is_last_selected_day(habit, today)
    if is_last_part is False:
        new_painting.type = HabitPaintingTypes.PARTIALLY_COMPLETED

    new_painting.save(update_fields=['date', 'type'])

    return render(request, 'habits/habit_new_painting.html', locals())

habits/views/habit_painting_detail.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from habits.models import HabitPainting


@login_required(redirect_field_name='', login_url='/login/')
def habit_painting_detail_view(request, pk=None):
    painting = get_object_or_404(HabitPainting, pk=pk, habit__author=request.user)
    return render(request, 'habits/habit_painting_detail.html', locals())

content/templates/habits/add_habit.html
{% extends 'base/index.html' %}

{% block content %}
<div class="content content--with-header content--with-footer">
    <div class="vertical-center">
        <form id="add-habit-form" class="vertical-center__element" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="habit-type-1-selector">
                <div style="display: none;">{{ form.type }}</div>
                <a class="habit-type-1-selector__element {% if form.type.value == 'daily' %}habit-type-1-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=daily">Дневная</a>
                <a class="habit-type-1-selector__element {% if form.type.value == 'weekly' %}habit-type-1-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=weekly">Недельная</a>
                <a class="habit-type-1-selector__element {% if form.type.value == 'monthly' %}habit-type-1-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=monthly">Месячная</a>
            </div>
            <div class="inputs">
                {% include 'common/input.html' with form_input=form.name with_label=True %}
                {% include 'common/input.html' with form_input=form.start_date with_label=True %}
                {% if form.type.value == 'daily' %}
                    {% include 'common/input.html' with form_input=form.frequency with_label=True label_suffix='(каждые n дней)' icon_type='number' %}
                {% elif form.type.value == 'weekly' %}
                    {% include 'common/input.html' with form_input=form.frequency with_label=True label_suffix='(каждые n недель)' icon_type='number' %}
                {% elif form.type.value == 'monthly' %}
                    {% include 'common/input.html' with form_input=form.frequency with_label=True label_suffix='(каждые n месяцев)' icon_type='number' %}
                {% endif %}
                {% if form.type.value == 'daily' %}
                    {% include 'common/input.html' with form_input=form.required_amount with_label=True label_suffix='(в день)' icon_type='number' %}
                {% elif form.type.value == 'weekly' %}
                    <hr>
                    <div class="habit-type-2-selector">
                        <a class="habit-type-2-selector__element {% if is_flexible %}habit-type-2-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=weekly&flexible=true">Неопределённая</a>
                        <a class="habit-type-2-selector__element {% if not is_flexible %}habit-type-2-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=weekly&flexible=false">Определённая</a>
                    </div>
                    {% if is_flexible %}
                        {% include 'common/input.html' with form_input=form.required_amount with_label=True label_suffix='(в неделю)' icon_type='number' %}
                    {% else %}
                        {% include 'common/input.html' with form_input=form.required_amount_per_day with_label=True icon_type='number' %}
                        {% include 'common/input.html' with form_input=form.selected_days with_label=True %}
                    {% endif %}
                {% elif form.type.value == 'monthly' %}
                    <hr>
                    <div class="habit-type-2-selector">
                        <a class="habit-type-2-selector__element {% if is_flexible %}habit-type-2-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=monthly&flexible=true">Неопределённая</a>
                        <a class="habit-type-2-selector__element {% if not is_flexible %}habit-type-2-selector__element--active{% endif %}" href="{% url 'add-habit' %}?type=monthly&flexible=false">Определённая</a>
                    </div>
                    {% if is_flexible %}
                        {% include 'common/input.html' with form_input=form.required_amount with_label=True label_suffix='(в месяц)' icon_type='number' %}
                    {% else %}
                        {% include 'common/input.html' with form_input=form.required_amount_per_day with_label=True icon_type='number' %}
                        {% include 'common/input.html' with form_input=form.selected_days with_label=True %}
                    {% endif %}
                {% endif %}
            </div>
        </form>
        <div class="vertical-center__element"></div>
        {% include 'common/button.html' with class_name='vertical-center__element' btn_type='button' form_name='add-habit-form' btn_value='Добавить' %}
    </div>
</div>
{% endblock %}

content/templates/habits/edit_habit.html
{% extends 'base/index.html' %}

{% block content %}
<div class="content content--with-header content--with-footer">
    <div class="vertical-center">
        <form id="edit-habit-form" class="vertical-center__element" method="post" autocomplete="off">
            {% csrf_token %}
            {% include 'common/input.html' with form_input=form.name with_label=True %}
            {% url 'delete-habit' habit.pk as btn_url %}
            {% include 'common/button.html' with btn_type='link' link_url=btn_url class_name='button--red' btn_value='Удалить' %}
        </form>
        <div class="vertical-center__element"></div>
        <div class="vertical-center__element">
            {% include 'common/button.html' with btn_type='button' form_name='edit-habit-form' btn_value='Сохранить' %}
        </div>
    </div>
</div>
{% endblock %}

content/templates/habits/habit_current_list.html
{% extends 'base/index.html' %}
{% load static %}
{% load habit_current %}

{% block content %}
<div class="content content--with-no-header content--with-footer">
    <div class="date">{% now "D — d b Y" %}</div>
    <form class="sort-form" method="get" autocomplete="off">
        <div class="left">Сортировать:</div>
        <div class="right">
            <a href="{% url 'habit-current-list' %}?order={{ order_form.order.value|reverse_order }}">
                Дедлайн
                {% if order_form.order.value == 'deadline' %}
                    <img src="{% static 'svg/sort-asc.svg' %}" alt="Sort asc">
                {% elif order_form.order.value == '-deadline' %}
                    <img src="{% static 'svg/sort-desc.svg' %}" alt="Sort desc">
                {% endif %}
            </a>
        </div>
    </form>
    <div class="habits">
        {% for habit in habits %}
            <div class="habit">
                <div class="habit__left">
                    <div class="habit__top">
                        <div class="habit__deadline">
                            <span>Дедлайн </span>
                            <span style="{% if habit.deadline == today %}color: #d09797;{% endif %} text-decoration: underline;">
                                {{ habit.deadline|date:'d b Y' }}
                            </span>
                        </div>
                        <div class="habit__name">{{ habit.name }}</div>
                    </div>
                    <div class="habit__bottom">
                        <div class="habit__streak">
                            <img class="streak__icon" src="{% static 'svg/fire.svg' %}" alt="Streak icon">
                            <div class="streak__number">{{ habit.current_streak }}</div>
                        </div>
                    </div>
                </div>
                <div class="habit__right">
                    <form method="post" autocomplete="off">
                        {% csrf_token %}
                        <input class="hidden" type="number" name="habit_id" value="{{ habit.pk }}">
                        <button style="background: transparent;" {% if habit.completed_amount >= habit.current_required_amount %}disabled{% endif %}>
                            <div class="habit__progress-ring c100 p{{ habit.complete_percentage }} center">
                                <span>{{ habit.completed_amount }}/{{ habit.current_required_amount }}</span>
                                <div class="slice">
                                    <div class="bar"></div>
                                    <div class="fill"></div>
                                </div>
                            </div>
                        </button>
                    </form>
                </div>
            </div>
        {% empty %}
            <div class="habits__empty">Нет привычек.</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

content/templates/habits/habit_detail.html
{% extends 'base/index.html' %}
{% load static %}
{% load habit_detail %}

{% block content %}
<div class="habit-detail content content--with-header content--with-footer">
    <div class="new-painting vertical-center">
        <div class="vertical-center__element">
            <div class="info-row">
                <div class="info-row__element">
                    {{ habit.get_type_display }}
                </div>
                <div class="info-row__element">
                    {{ habit.start_date|date:"d.m.Y" }}
                </div>
                <div class="info-row__element info-row__element--with-icon">
                    <img src="{% static 'svg/paintings.svg' %}" alt="Paintings">
                    <div>{{ habit.painting_cnt }}</div>
                </div>
                <div class="info-row__element info-row__element--with-icon">
                    <img src="{% static 'svg/fire.svg' %}" alt="Streak">
                    <div>{{ habit.current_streak }}</div>
                </div>
            </div>
            <div class="title">{{ habit.name }}</div>
            <table class="calendar">
                <tr>
                    {% with 'Пн Вт Ср Чт Пт Сб Вс' as weekdays %}
                        {% for weekday in weekdays.split %}
                            <td>{{ weekday }}</td>
                        {% endfor %}
                    {% endwith %}
                </tr>
                {% for row in calendar_rows %}
                    <tr>
                        {% for day in row %}
                            <td>
                                <div class="td-inner">
                                    {% if day.type == 'partially_completed' %}
                                        <img class="calendar__painting" src="{% static 'img/partial-painting-icon.png' %}" alt="Daily painting">
                                    {% elif day.type == 'completed' and day.painting and day.painting.painting %}
                                        <a href="{% url 'habit-painting-detail' day.painting.pk %}">
                                            {% include 'common/painting.html' with painting_url=day.painting.painting.url class_name='calendar__painting' %}
                                        </a>
                                    {% elif day.type == 'missed' %}
                                        <img class="calendar__painting" src="{% static 'img/missed-painting-icon.png' %}" alt="Daily painting">
                                    {% elif day.type == 'expected_part' or day.type == 'expected_full' %}
                                        <img class="calendar__painting" src="{% static 'img/expected-painting-icon.png' %}" alt="Daily painting">
                                    {% elif day.type == 'none' %}
                                        <div class="calendar__no-day"></div>
                                    {% else %}
                                        {% get_date calendar_date.year calendar_date.month day.num as day_date %}
                                        {% if day_date < habit.start_date %}
                                            <div class="calendar__invalid-day"></div>
                                        {% else %}
                                            <div class="calendar__empty-day"></div>
                                        {% endif %}
                                    {% endif %}
                                    {% if day.type != 'none' %}
                                        {% get_date calendar_date.year calendar_date.month day.num as day_date %}
                                        <div class="calendar__day-number {% if day_date == today %}calendar__day-number--today{% endif %}">
                                            {{ day.num }}
                                        </div>
                                    {% endif %}
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="vertical-center__element"></div>
        <div class="vertical-center__element">
            <div class="controls">
                <a class="controls__btn" href="{% url 'habit-detail' pk %}?calendar_date={{ calendar_date|prev_month|date:'Y-m-01' }}">
                    <img src="{% static 'svg/prev.svg' %}" alt="Previous">
                </a>
                <div class="controls__label">
                    {{ calendar_date|date:'F, Y' }}
                </div>
                <a class="controls__btn" href="{% url 'habit-detail' pk %}?calendar_date={{ calendar_date|next_month|date:'Y-m-01' }}">
                    <img src="{% static 'svg/next.svg' %}" alt="Next">
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock  %}